// Compares web/src/iapws97.js against web/dev/reference.json (generated by
// gen_reference.py from the Python `iapws` package). Run:
//   node web/dev/validate.mjs

import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const IAPWS97 = require('../src/iapws97.js');

const cases = JSON.parse(readFileSync(new URL('./reference.json', import.meta.url)));

let worstH = 0, worstS = 0, worstV = 0, worstT = 0;
let worstHCase = null, worstTCase = null;
let failures = 0;

for (const c of cases) {
  let result;
  try {
    if (c.kind === 'TP') result = IAPWS97.solve({ T: c.T, P: c.P });
    else if (c.kind === 'Px') result = IAPWS97.solve({ P: c.P, x: c.x });
    else if (c.kind === 'Ph') result = IAPWS97.solve({ P: c.P, h: c.h });
    else if (c.kind === 'Ps') result = IAPWS97.solve({ P: c.P, s: c.s });
  } catch (e) {
    failures++;
    console.error(`ERROR on ${c.kind} case ${JSON.stringify(c)}: ${e.message}`);
    continue;
  }

  if (c.h !== undefined) {
    const err = Math.abs(result.h - c.h);
    if (err > worstH) { worstH = err; worstHCase = { c, result }; }
  }
  if (c.s !== undefined) worstS = Math.max(worstS, Math.abs(result.s - c.s));
  if (c.v !== undefined) worstV = Math.max(worstV, Math.abs(result.v - c.v) / c.v);
  if (c.T !== undefined) {
    const err = Math.abs(result.T - c.T);
    if (err > worstT) { worstT = err; worstTCase = { c, result }; }
  }
  if (c.x_expected !== undefined && result.x !== undefined) {
    const err = Math.abs(result.x - c.x_expected);
    if (err > 0.01) {
      failures++;
      console.error(`QUALITY MISMATCH: ${JSON.stringify(c)} -> got x=${result.x}`);
    }
  }
}

console.log(`Cases checked: ${cases.length}, hard failures: ${failures}`);
console.log(`Max |Delta h| = ${worstH.toFixed(6)} kJ/kg`);
console.log(`Max |Delta s| = ${worstS.toFixed(6)} kJ/kg-K`);
console.log(`Max relative |Delta v| = ${(worstV * 100).toFixed(6)} %`);
console.log(`Max |Delta T| = ${worstT.toFixed(6)} K`);
if (worstHCase) console.log('Worst h case:', JSON.stringify(worstHCase.c), '-> got h=', worstHCase.result.h);
if (worstTCase) console.log('Worst T case:', JSON.stringify(worstTCase.c), '-> got T=', worstTCase.result.T);

const TOL_H = 0.05;   // kJ/kg
const TOL_S = 0.0005; // kJ/kg-K
const TOL_T = 0.01;   // K
if (failures > 0 || worstH > TOL_H || worstS > TOL_S || worstT > TOL_T) {
  console.error('\nVALIDATION FAILED');
  process.exit(1);
} else {
  console.log('\nVALIDATION PASSED');
}
